// Editorial context is our own descriptive summary, not Scripture or a model-generated explanation.
export const selections = [
  ['PSA', 'Psalms', 23, 1, 4, 'A psalm describing God’s care through rest, guidance, and danger.'],
  [
    'PSA',
    'Psalms',
    23,
    5,
    6,
    'The closing lines of Psalm 23 describe provision, kindness, and dwelling with God.',
  ],
  [
    'PSA',
    'Psalms',
    34,
    4,
    8,
    'A song of thanksgiving recalling deliverance from fear and inviting trust in God.',
  ],
  [
    'PSA',
    'Psalms',
    34,
    17,
    19,
    'This psalm describes God’s nearness to people who are brokenhearted and afflicted.',
  ],
  [
    'PSA',
    'Psalms',
    42,
    1,
    5,
    'The psalmist expresses longing for God, tears, and memories of worship with others.',
  ],
  ['PSA', 'Psalms', 46, 1, 3, 'A communal song that speaks of refuge amid upheaval and danger.'],
  [
    'PSA',
    'Psalms',
    46,
    8,
    11,
    'The closing section describes God bringing wars to an end and calls listeners to stillness.',
  ],
  ['PSA', 'Psalms', 61, 1, 4, 'A prayer from a faint heart asking for refuge and shelter in God.'],
  [
    'PSA',
    'Psalms',
    68,
    4,
    6,
    'A song portraying God as a defender of vulnerable people and a home for the lonely.',
  ],
  [
    'PSA',
    'Psalms',
    103,
    8,
    14,
    'The psalm celebrates mercy, forgiveness, and compassion while acknowledging human frailty.',
  ],
  [
    'PSA',
    'Psalms',
    121,
    1,
    8,
    'A song of ascents expressing trust in God’s watchful care during life’s journeys.',
  ],
  ['PSA', 'Psalms', 139, 1, 6, 'A prayer reflecting on being deeply known by God.'],
  [
    'PSA',
    'Psalms',
    139,
    7,
    12,
    'The psalmist considers God’s presence across distance and darkness.',
  ],
  [
    'PSA',
    'Psalms',
    147,
    1,
    6,
    'Praise for God who gathers the scattered and heals the brokenhearted.',
  ],
  [
    'PRO',
    'Proverbs',
    3,
    5,
    8,
    'Wisdom instruction about trust, humility, and acknowledging God when choosing a path.',
  ],
  [
    'PRO',
    'Proverbs',
    16,
    1,
    3,
    'Wisdom sayings reflecting on human plans, motives, and committing work to God.',
  ],
  [
    'ECC',
    'Ecclesiastes',
    3,
    1,
    8,
    'A poem recognizing contrasting seasons in human life, including mourning and celebration.',
  ],
  [
    'ISA',
    'Isaiah',
    40,
    28,
    31,
    'Words of comfort addressing weariness and strength in a chapter of consolation.',
  ],
  ['ISA', 'Isaiah', 41, 8, 10, 'God addresses Israel as his servant and reassures them amid fear.'],
  [
    'ISA',
    'Isaiah',
    43,
    1,
    4,
    'God addresses Jacob and Israel with reassurance of belonging amid danger.',
  ],
  [
    'JER',
    'Jeremiah',
    29,
    4,
    7,
    'A letter to exiles in Babylon telling them to build lives and seek their city’s welfare.',
  ],
  [
    'JER',
    'Jeremiah',
    29,
    10,
    14,
    'A promise addressed to the exiled community concerning restoration after a long period in Babylon.',
  ],
  [
    'LAM',
    'Lamentations',
    3,
    19,
    26,
    'Within lament over suffering and destruction, the speaker recalls mercy and expresses hope.',
  ],
  [
    'GEN',
    'Genesis',
    22,
    9,
    14,
    'In the account of Abraham and Isaac, a ram is provided and the place receives a name recalling provision.',
  ],
  [
    'EXO',
    'Exodus',
    16,
    1,
    5,
    'Israel expresses hunger in the wilderness and receives instructions about daily provision.',
  ],
  [
    'DEU',
    'Deuteronomy',
    31,
    6,
    8,
    'Moses encourages Israel and Joshua as leadership passes to Joshua.',
  ],
  [
    '1SA',
    '1 Samuel',
    7,
    10,
    12,
    'After deliverance from the Philistines, Samuel sets up a memorial stone called Ebenezer.',
  ],
  [
    '1KI',
    '1 Kings',
    19,
    4,
    8,
    'Elijah, exhausted and distressed, receives food and rest before continuing his journey.',
  ],
  [
    'MAT',
    'Matthew',
    6,
    25,
    34,
    'In the Sermon on the Mount, Jesus teaches about anxiety, daily needs, and seeking God’s kingdom.',
  ],
  [
    'MAT',
    'Matthew',
    11,
    28,
    30,
    'Jesus invites weary and burdened people to learn from him and find rest.',
  ],
  [
    'MAT',
    'Matthew',
    5,
    3,
    9,
    'The opening blessings of the Sermon on the Mount address mourning, mercy, and peacemaking.',
  ],
  [
    'LUK',
    'Luke',
    5,
    4,
    11,
    'After an unsuccessful night of fishing, Peter encounters Jesus and is called to follow him.',
  ],
  [
    'LUK',
    'Luke',
    15,
    17,
    24,
    'In Jesus’s parable, a son returns home and is welcomed by his father.',
  ],
  [
    'JHN',
    'John',
    4,
    7,
    14,
    'Jesus speaks with a Samaritan woman at a well about water and the life he offers.',
  ],
  ['JHN', 'John', 6, 5, 13, 'Jesus feeds a crowd using a boy’s small offering of bread and fish.'],
  [
    'JHN',
    'John',
    14,
    1,
    6,
    'During his farewell conversation, Jesus speaks to troubled disciples about trust and his Father’s house.',
  ],
  [
    'JHN',
    'John',
    14,
    25,
    27,
    'Jesus promises the Holy Spirit and speaks of peace during his farewell conversation.',
  ],
  [
    'JHN',
    'John',
    15,
    9,
    13,
    'Jesus teaches his disciples about remaining in his love and loving one another.',
  ],
  [
    'ROM',
    'Romans',
    8,
    18,
    25,
    'Paul discusses suffering, creation’s longing, and patient hope for redemption.',
  ],
  [
    'ROM',
    'Romans',
    8,
    31,
    39,
    'Paul expresses assurance of God’s love amid hardship and opposition.',
  ],
  [
    'ROM',
    'Romans',
    12,
    9,
    18,
    'Instructions for sincere love, hospitality, solidarity, and living peaceably with others.',
  ],
  [
    '2CO',
    '2 Corinthians',
    1,
    3,
    7,
    'Paul speaks of receiving comfort in affliction and offering comfort to others.',
  ],
  [
    'GAL',
    'Galatians',
    6,
    1,
    5,
    'Instructions about gently restoring others and carrying one another’s burdens.',
  ],
  [
    'GAL',
    'Galatians',
    6,
    7,
    10,
    'Paul encourages perseverance in doing good, using the image of sowing and harvest.',
  ],
  [
    'EPH',
    'Ephesians',
    2,
    17,
    22,
    'Paul describes reconciliation in Christ and belonging to God’s household.',
  ],
  [
    'PHP',
    'Philippians',
    4,
    4,
    9,
    'Paul encourages rejoicing, prayer, thoughtful attention, and practicing what has been learned.',
  ],
  [
    'PHP',
    'Philippians',
    4,
    10,
    13,
    'Paul describes learning contentment in both need and abundance while thanking his supporters.',
  ],
  [
    'HEB',
    'Hebrews',
    11,
    13,
    16,
    'The writer describes faithful people as strangers and pilgrims seeking a better country.',
  ],
  ['JAS', 'James', 1, 2, 5, 'James discusses trials, perseverance, and asking God for wisdom.'],
  [
    '1PE',
    '1 Peter',
    5,
    6,
    10,
    'Peter encourages humility, casting anxiety on God, vigilance, and endurance in suffering.',
  ],
].map(([bookCode, book, chapter, firstVerse, lastVerse, context]) => ({
  id: `${bookCode}.${chapter}.${firstVerse}-${lastVerse}`,
  bookCode,
  book,
  chapter,
  firstVerse,
  lastVerse,
  context,
}));
