// Generated by pnpm db:types from the local migrated schema. Do not edit.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  ebenezer_api: {
    Tables: {
      comments: {
        Row: {
          author_id: string;
          body: string;
          created_at: string;
          id: string;
          post_id: string;
        };
        ComputedFields: never;
        Insert: {
          author_id: string;
          body: string;
          created_at?: string;
          id?: string;
          post_id: string;
        };
        Update: {
          author_id?: string;
          body?: string;
          created_at?: string;
          id?: string;
          post_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'comments_author_id_fkey';
            columns: ['author_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'comments_post_id_fkey';
            columns: ['post_id'];
            isOneToOne: false;
            referencedRelation: 'posts';
            referencedColumns: ['id'];
          },
        ];
      };
      connections: {
        Row: {
          created_at: string;
          id: string;
          recipient_id: string;
          requester_id: string;
          status: string;
          updated_at: string;
        };
        ComputedFields: never;
        Insert: {
          created_at?: string;
          id?: string;
          recipient_id: string;
          requester_id: string;
          status?: string;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          recipient_id?: string;
          requester_id?: string;
          status?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'connections_recipient_id_fkey';
            columns: ['recipient_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'connections_requester_id_fkey';
            columns: ['requester_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      group_members: {
        Row: {
          created_at: string;
          group_id: string;
          invited_by: string | null;
          joined_at: string | null;
          role: string;
          status: string;
          user_id: string;
        };
        ComputedFields: never;
        Insert: {
          created_at?: string;
          group_id: string;
          invited_by?: string | null;
          joined_at?: string | null;
          role?: string;
          status: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          group_id?: string;
          invited_by?: string | null;
          joined_at?: string | null;
          role?: string;
          status?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'group_members_group_id_fkey';
            columns: ['group_id'];
            isOneToOne: false;
            referencedRelation: 'groups';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'group_members_invited_by_fkey';
            columns: ['invited_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'group_members_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      groups: {
        Row: {
          created_at: string;
          description: string;
          id: string;
          meeting_note: string | null;
          member_count: number;
          name: string;
          owner_id: string;
          updated_at: string;
          version: number;
          visibility: string;
        };
        ComputedFields: never;
        Insert: {
          created_at?: string;
          description?: string;
          id?: string;
          meeting_note?: string | null;
          member_count?: number;
          name: string;
          owner_id: string;
          updated_at?: string;
          version?: number;
          visibility: string;
        };
        Update: {
          created_at?: string;
          description?: string;
          id?: string;
          meeting_note?: string | null;
          member_count?: number;
          name?: string;
          owner_id?: string;
          updated_at?: string;
          version?: number;
          visibility?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'groups_owner_id_fkey';
            columns: ['owner_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      post_recipients: {
        Row: {
          granted_at: string;
          post_id: string;
          revoked_at: string | null;
          user_id: string;
        };
        ComputedFields: never;
        Insert: {
          granted_at?: string;
          post_id: string;
          revoked_at?: string | null;
          user_id: string;
        };
        Update: {
          granted_at?: string;
          post_id?: string;
          revoked_at?: string | null;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'post_recipients_post_id_fkey';
            columns: ['post_id'];
            isOneToOne: false;
            referencedRelation: 'posts';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'post_recipients_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      posts: {
        Row: {
          audience: string;
          author_id: string;
          body: string;
          comment_count: number;
          created_at: string;
          deleted_at: string | null;
          group_id: string | null;
          id: string;
          kind: string;
          prayer_count: number;
          scripture_reference: string | null;
          scripture_text: string | null;
          tone: string | null;
          updated_at: string;
          version: number;
        };
        ComputedFields: never;
        Insert: {
          audience: string;
          author_id: string;
          body: string;
          comment_count?: number;
          created_at?: string;
          deleted_at?: string | null;
          group_id?: string | null;
          id?: string;
          kind: string;
          prayer_count?: number;
          scripture_reference?: string | null;
          scripture_text?: string | null;
          tone?: string | null;
          updated_at?: string;
          version?: number;
        };
        Update: {
          audience?: string;
          author_id?: string;
          body?: string;
          comment_count?: number;
          created_at?: string;
          deleted_at?: string | null;
          group_id?: string | null;
          id?: string;
          kind?: string;
          prayer_count?: number;
          scripture_reference?: string | null;
          scripture_text?: string | null;
          tone?: string | null;
          updated_at?: string;
          version?: number;
        };
        Relationships: [
          {
            foreignKeyName: 'posts_author_id_fkey';
            columns: ['author_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'posts_group_id_fkey';
            columns: ['group_id'];
            isOneToOne: false;
            referencedRelation: 'groups';
            referencedColumns: ['id'];
          },
        ];
      };
      prayer_links: {
        Row: {
          created_at: string;
          expires_at: string;
          id: string;
          label: string;
          post_id: string;
          revoked_at: string | null;
          token_hash: string;
        };
        ComputedFields: never;
        Insert: {
          created_at?: string;
          expires_at: string;
          id?: string;
          label: string;
          post_id: string;
          revoked_at?: string | null;
          token_hash: string;
        };
        Update: {
          created_at?: string;
          expires_at?: string;
          id?: string;
          label?: string;
          post_id?: string;
          revoked_at?: string | null;
          token_hash?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'prayer_links_post_id_fkey';
            columns: ['post_id'];
            isOneToOne: false;
            referencedRelation: 'posts';
            referencedColumns: ['id'];
          },
        ];
      };
      prayers: {
        Row: {
          created_at: string;
          id: string;
          note: string | null;
          post_id: string;
          prayer_link_id: string | null;
          user_id: string | null;
        };
        ComputedFields: never;
        Insert: {
          created_at?: string;
          id?: string;
          note?: string | null;
          post_id: string;
          prayer_link_id?: string | null;
          user_id?: string | null;
        };
        Update: {
          created_at?: string;
          id?: string;
          note?: string | null;
          post_id?: string;
          prayer_link_id?: string | null;
          user_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'prayers_post_id_fkey';
            columns: ['post_id'];
            isOneToOne: false;
            referencedRelation: 'posts';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'prayers_prayer_link_id_fkey';
            columns: ['prayer_link_id'];
            isOneToOne: true;
            referencedRelation: 'prayer_links';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'prayers_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      profiles: {
        Row: {
          created_at: string;
          display_name: string;
          handle: string;
          id: string;
          updated_at: string;
        };
        ComputedFields: never;
        Insert: {
          created_at?: string;
          display_name: string;
          handle: string;
          id: string;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          display_name?: string;
          handle?: string;
          id?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      push_subscriptions: {
        Row: {
          auth: string;
          created_at: string;
          discreet: boolean;
          endpoint: string;
          evening_time: string;
          id: string;
          language: string;
          last_evening_sent: string | null;
          last_morning_sent: string | null;
          morning_time: string;
          p256dh: string;
          time_zone: string;
          updated_at: string;
        };
        ComputedFields: never;
        Insert: {
          auth: string;
          created_at?: string;
          discreet?: boolean;
          endpoint: string;
          evening_time?: string;
          id?: string;
          language?: string;
          last_evening_sent?: string | null;
          last_morning_sent?: string | null;
          morning_time?: string;
          p256dh: string;
          time_zone: string;
          updated_at?: string;
        };
        Update: {
          auth?: string;
          created_at?: string;
          discreet?: boolean;
          endpoint?: string;
          evening_time?: string;
          id?: string;
          language?: string;
          last_evening_sent?: string | null;
          last_morning_sent?: string | null;
          morning_time?: string;
          p256dh?: string;
          time_zone?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      add_comment: { Args: { p_body: string; p_post: string }; Returns: Json };
      answer_prayer_link: { Args: { p_note?: string; p_token: string }; Returns: Json };
      create_group: {
        Args: {
          p_description?: string;
          p_meeting_note?: string;
          p_name: string;
          p_visibility?: string;
        };
        Returns: Json;
      };
      create_post: {
        Args: {
          p_audience: string;
          p_body: string;
          p_group_id?: string;
          p_kind: string;
          p_recipient_ids?: string[];
          p_scripture_reference?: string;
          p_scripture_text?: string;
          p_tone?: string;
        };
        Returns: Json;
      };
      create_prayer_link: {
        Args: { p_days?: number; p_label: string; p_post: string };
        Returns: Json;
      };
      delete_comment: { Args: { p_id: string }; Returns: undefined };
      delete_group: { Args: { p_id: string }; Returns: undefined };
      delete_post: { Args: { p_id: string }; Returns: undefined };
      feed: {
        Args: {
          p_before?: string;
          p_before_id?: string;
          p_group?: string;
          p_kind?: string;
          p_limit?: number;
        };
        Returns: Json;
      };
      invite_to_group: { Args: { p_id: string; p_user: string }; Returns: undefined };
      join_group: { Args: { p_id: string }; Returns: Json };
      leave_group: { Args: { p_id: string }; Returns: undefined };
      list_comments: { Args: { p_post: string }; Returns: Json };
      list_connections: { Args: Record<PropertyKey, never>; Returns: Json };
      list_group_members: { Args: { p_id: string }; Returns: Json };
      list_groups: { Args: Record<PropertyKey, never>; Returns: Json };
      open_prayer_link: { Args: { p_token: string }; Returns: Json };
      remove_connection: { Args: { p_id: string }; Returns: undefined };
      remove_group_member: { Args: { p_id: string; p_user: string }; Returns: undefined };
      report_post: {
        Args: { p_detail?: string; p_post: string; p_reason: string };
        Returns: undefined;
      };
      request_connection: { Args: { p_user: string }; Returns: Json };
      respond_connection: { Args: { p_accept: boolean; p_id: string }; Returns: Json };
      revoke_prayer_link: { Args: { p_id: string }; Returns: undefined };
      search_people: { Args: { p_query: string }; Returns: Json };
      set_group_role: {
        Args: { p_id: string; p_role: string; p_user: string };
        Returns: undefined;
      };
      set_prayer: { Args: { p_post: string; p_praying: boolean }; Returns: Json };
      update_group: {
        Args: {
          p_description: string;
          p_id: string;
          p_meeting_note: string;
          p_name: string;
          p_visibility: string;
        };
        Returns: Json;
      };
      update_post: { Args: { p_body: string; p_id: string }; Returns: Json };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
  ebenezer_private: {
    Tables: {
      reports: {
        Row: {
          created_at: string;
          detail: string | null;
          id: string;
          post_id: string | null;
          reason: string;
          reporter_id: string;
          status: string;
        };
        ComputedFields: never;
        Insert: {
          created_at?: string;
          detail?: string | null;
          id?: string;
          post_id?: string | null;
          reason: string;
          reporter_id: string;
          status?: string;
        };
        Update: {
          created_at?: string;
          detail?: string | null;
          id?: string;
          post_id?: string | null;
          reason?: string;
          reporter_id?: string;
          status?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      are_friends: { Args: { a: string; b: string }; Returns: boolean };
      can_see_post: {
        Args: {
          actor: string;
          p: Omit<
            Database['ebenezer_api']['Tables']['posts']['Row'],
            Database['ebenezer_api']['Tables']['posts']['ComputedFields']
          >;
        };
        Returns: boolean;
      };
      clean: { Args: { value: string }; Returns: string };
      comment_json: {
        Args: {
          c: Omit<
            Database['ebenezer_api']['Tables']['comments']['Row'],
            Database['ebenezer_api']['Tables']['comments']['ComputedFields']
          >;
          post_author: string;
          viewer: string;
        };
        Returns: Json;
      };
      connection_json: {
        Args: {
          c: Omit<
            Database['ebenezer_api']['Tables']['connections']['Row'],
            Database['ebenezer_api']['Tables']['connections']['ComputedFields']
          >;
          viewer: string;
        };
        Returns: Json;
      };
      current_member: { Args: Record<PropertyKey, never>; Returns: string };
      group_json: {
        Args: {
          g: Omit<
            Database['ebenezer_api']['Tables']['groups']['Row'],
            Database['ebenezer_api']['Tables']['groups']['ComputedFields']
          >;
          viewer: string;
        };
        Returns: Json;
      };
      group_manager: { Args: { actor: string; target: string }; Returns: boolean };
      is_active_member: { Args: { actor: string; target: string }; Returns: boolean };
      link_for: {
        Args: { p_token: string };
        Returns: Database['ebenezer_api']['Tables']['prayer_links']['Row'];
        SetofOptions: {
          from: '*';
          to: 'prayer_links';
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      person_json: { Args: { person: string }; Returns: Json };
      post_json: {
        Args: {
          p: Omit<
            Database['ebenezer_api']['Tables']['posts']['Row'],
            Database['ebenezer_api']['Tables']['posts']['ComputedFields']
          >;
          viewer: string;
        };
        Returns: Json;
      };
      visible_post: {
        Args: { actor: string; target: string };
        Returns: Database['ebenezer_api']['Tables']['posts']['Row'];
        SetofOptions: {
          from: '*';
          to: 'posts';
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, 'public'>];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    ? (DefaultSchema['Tables'] & DefaultSchema['Views'])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema['Tables'] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema['Tables'] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    keyof DefaultSchema['Enums'] | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums']
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums'][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums']
    ? DefaultSchema['Enums'][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    keyof DefaultSchema['CompositeTypes'] | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes']
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes'][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema['CompositeTypes']
    ? DefaultSchema['CompositeTypes'][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  ebenezer_api: {
    Enums: {},
  },
  ebenezer_private: {
    Enums: {},
  },
} as const;
